### ISSUE TITLE
Enregistrement

### ISSUE THREAD

**Issue by Florent-V** [WildCodeSchool/2022-09-php-remote-p2-my-tv-tagere#36]
Lorsque l'on s'enregistre, on n'est pas directement redirigé vers son compte mais vers la page d'accueil. On peut croire que notre inscription à échoué et si on essaie de s'enregistrer à nouveau avec la même adresse, il y a une erreur de clé unique. Peut être faire la vérif côté serveur pour indiquer à l'utilisateur qu'une adresse existe déjà à son nom.

**Comment by jfm-wcs** [comment]
Je viens d'essayer de me créer un compte mais je n'ai pas pu car `JF` n'a pas été accepté pour mon prénom 😢. 
"Votre prémon est obligatoire" est-il écrit..
Peut-être qu'il faudrait mentionner "minimum 3 caractères" sour le champ "prénom" ?

**Comment by jfm-wcs** [comment]
Et du coup il faut que je remplisse à nouveau tout le formulaire. Double snif 😢😢
😉
