### ISSUE TITLE
Liens footer

### ISSUE THREAD

**Issue by jfm-wcs** [WildCodeSchool/2022-09-php-remote-p2-my-tv-tagere#37]
Peut-être avez-vous prévu d'ajouter ces pages, mais au cas où, je vous signale que les liens contact et infos légales du footer ne sont pas branchés 😉.

**Comment by SkyriMeg** [comment]
Et la signature "©2022 ⚡PHPPower⚡" du footer change de couleur au survol, ça donne l'impression que c'est un lien 🙄
