### ISSUE TITLE
Scroll horizontal

### ISSUE THREAD

**Issue by Florent-V** [WildCodeSchool/2022-09-php-remote-p2-my-tv-tagere#38]
Lorsqu'on a ajouté une série à nos favoris, cela rajoute un bandeau avec des séries recommandés mais décale également le DOM. Et lors qu'on scroll sur comédie, c'est action qui défile

**Comment by Axl-Crz** [comment]
Effectivement il y a un décalage sur les scroll, a chaque fois ça scroll sur la ligne en dessous de celle où on a la souris
